#!/usr/bin/env bash

WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=74069 (3scale-operator-metadata-container)
${WORK_DIR}/process-image-manifests registry-proxy.engineering.redhat.com/rh-osbs/3scale-amp2-3scale-rhel7-operator-metadata:1.11.0-2

#https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=69209 (fuse-online-operator-container)
${WORK_DIR}/process-image-manifests registry-proxy.engineering.redhat.com/rh-osbs/fuse7-fuse-online-operator:1.6-8

#https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=74050 (amq7-amq-online-1-controller-manager-operator-metadata-container)
${WORK_DIR}/process-image-manifests registry-proxy.engineering.redhat.com/rh-osbs/amq7-amq-online-1-controller-manager-rhel7-operator-metadata:1.4-10

#https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=74060 (codeready-workspaces-operator-metadata-container)
${WORK_DIR}/process-image-manifests registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-operator-metadata:2.1-2

#https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=73236(amqstreams-operator-container)
${WORK_DIR}/process-image-manifests registry-proxy.engineering.redhat.com/rh-osbs/amq7-amq-streams-operator:1.3.0-11
